// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (owner, asset_type, account_type)
VALUES ($1, $2, $3)
RETURNING id, owner, asset_type, account_type, created_at, updated_at
`

type CreateAccountParams struct {
	Owner       string `json:"owner"`
	AssetType   string `json:"asset_type"`
	AccountType string `json:"account_type"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Owner, arg.AssetType, arg.AccountType)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.AssetType,
		&i.AccountType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, owner, asset_type, account_type, created_at, updated_at FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.AssetType,
		&i.AccountType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(28, 18) AS balance
FROM ledger_entries
WHERE account_id = $1
`

func (q *Queries) GetBalance(ctx context.Context, accountID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getBalance, accountID)
	var balance pgtype.Numeric
	err := row.Scan(&balance)
	return balance, err
}

const listAccountsByOwner = `-- name: ListAccountsByOwner :many
SELECT id, owner, asset_type, account_type, created_at, updated_at FROM accounts
WHERE owner = $1
ORDER BY created_at
`

func (q *Queries) ListAccountsByOwner(ctx context.Context, owner string) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByOwner, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.AssetType,
			&i.AccountType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
