// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger_entries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entries (transaction_id, account_id, amount)
VALUES ($1, $2, $3)
RETURNING id, transaction_id, account_id, amount, created_at
`

type CreateLedgerEntryParams struct {
	TransactionID pgtype.UUID    `json:"transaction_id"`
	AccountID     pgtype.UUID    `json:"account_id"`
	Amount        pgtype.Numeric `json:"amount"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry, arg.TransactionID, arg.AccountID, arg.Amount)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getEntriesByAccount = `-- name: GetEntriesByAccount :many
SELECT id, transaction_id, account_id, amount, created_at FROM ledger_entries
WHERE account_id = $1
ORDER BY created_at
`

func (q *Queries) GetEntriesByAccount(ctx context.Context, accountID pgtype.UUID) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, getEntriesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntriesByTransaction = `-- name: GetEntriesByTransaction :many
SELECT id, transaction_id, account_id, amount, created_at FROM ledger_entries
WHERE transaction_id = $1
ORDER BY created_at
`

func (q *Queries) GetEntriesByTransaction(ctx context.Context, transactionID pgtype.UUID) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, getEntriesByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
