// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          pgtype.UUID        `json:"id"`
	Owner       string             `json:"owner"`
	AssetType   string             `json:"asset_type"`
	AccountType string             `json:"account_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type LedgerEntry struct {
	ID            pgtype.UUID        `json:"id"`
	TransactionID pgtype.UUID        `json:"transaction_id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID             pgtype.UUID        `json:"id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Type           string             `json:"type"`
	Status         string             `json:"status"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
